kind: pipeline
name: default

steps:
  - name: stack-test
    image: fpco/stack-build:lts
    commands:
      - apt-get update && apt-get install -y clang
      - stack build -j1
      - stack build -j1 --test
    volumes:
      - name: cache
        path: /root

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
    - master
