name: zen
version: 0.1.0.0
github: 'CameronDiver/zen'
license: BSD3
author: 'Cameron Diver'
maintainer: 'cameron@0xcd.dev'
copyright: '2020 Cameron Diver'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/CameronDiver/zen#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - prettyprinter
  - megaparsec
  - string-conversions
  - llvm-hs-pure
  - llvm-hs-pretty

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - FlexibleContexts
  - MultiParamTypeClasses
  - TupleSections
  - BlockArguments
  - RecursiveDo
  - DuplicateRecordFields

ghc-options:
  - -Wall

library:
  source-dirs: src
  dependencies:
    - containers
    - parser-combinators
    - mtl
    - directory
    - process
    - temporary
    - extra

executables:
  zen:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - zen
      - optparse-applicative
      - pretty-simple

tests:
  zen-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - zen
      - tasty
      - tasty-golden
      - tasty-hunit
      - filepath
